name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
      - name: Cache rust build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: rust-build-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}
      - name: Install musl tools
        run: sudo apt-get install -y musl-tools
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          use-cross: ${{ matrix.target != 'x86_64-unknown-linux-musl' }}
          args: --target ${{ matrix.target }}
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.target != 'x86_64-unknown-linux-musl' }}
          args: --target ${{ matrix.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kubectl-why-can-${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/kubectl-why-can
          retention-days: 7
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
      - name: Cache rust build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: rust-build-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}
      - name: Run tests
        uses: actions-rs/cargo@v1
        if: ${{ matrix.target == 'x86_64-apple-darwin' }}
        with:
          command: test
          args: --target ${{ matrix.target }}
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kubectl-why-can-${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/kubectl-why-can
          retention-days: 7
